### ISSUE TITLE
Cannot find module 'chalk'

### ISSUE THREAD

**Issue by varjmes** [addyosmani/a11y#13]
Howdy! This looks like an awesome tool, thank you!

I installed the module `npm install -g a11y` and it installed without issue.
However when I tried to run it: `a11y http://www.google.com`

I got the following:

`module.js:340
    throw err;
          ^
Error: Cannot find module 'chalk'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/a11y/cli.js:7:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)`

I tried running `npm cache clean` which I found after a few google searches but it did not work.
Not sure if this is specific to me or is a wider problem.

Sorry to post an issue so quickly after you released it to the world!

**Comment by DTD1031** [comment]
interesting

**Comment by KingJavaJava** [comment]
Also experiencing this issue

**Comment by rmnill202** [comment]
I'm experiencing this issue as well.

**Comment by knwiswolo** [comment]
Have you been able to find a solution pls? I have been struggling to fix this all morning.

**Comment by leodutra** [comment]
Solution?

**Comment by knwiswolo** [comment]
Well, sort of.
Duplicated my codebase, wiped by mac clean of any node.js/npm traces i.e. all installations and cache.
Then installed an older, more stable version of Node.js.
Slowly but surely, it all worked out. But now I double check my code a billion times before I build any projects (PTSD if you will).
Good luck!

**Comment by vivekiyer114** [comment]
what's final solution for this ?
Please help, i am facing the same issue.

Operating System:- MacOS

**Comment by Turngait** [comment]
I had the same problem. I used an 'npm i' and then everything started.

**Comment by gjvoit** [comment]
FWIW, I just had to upgrade node. This did not fix the yarn issue, but updating to the latest NPM/Node combo got the `npx` script working for me.

Edit, adding means by which I installed node: https://nodejs.org/en/
