### ISSUE TITLE
Fix breaking test in master

### ISSUE THREAD

**Issue by addyosmani** [addyosmani/a11y#45]
`test local input generates a report that includes all failures for a given violation   false == true`

**Comment by addyosmani** [comment]
@sindresorhus This seems to have started breaking in https://travis-ci.org/addyosmani/a11y/jobs/63219497. https://travis-ci.org/addyosmani/a11y/jobs/62002585 was still passing. Seems very weird given https://github.com/addyosmani/a11y/commit/058a6cd744f613e0be8b1a7b8a2ef9ea2ba52285 doesn't seem like it should break anything.

**Comment by sindresorhus** [comment]
Tests seems to be passing now: https://travis-ci.org/addyosmani/a11y/builds/72230315

**Comment by addyosmani** [comment]
:sparkle:
